udp_driver_node:
  ros__parameters:
    udp_config:
      send_port: 5555
      send_ip: 192.192.192.10
      recv_port: 0  # Not used for sending
      recv_ip: 0.0.0.0  # Not used for sending
      multicast_interface_ip: 192.192.192.11
    topic_name: /etsi_its_conversion/udp/out
    msg_type: udp_msgs/msg/UdpPacket
    use_multicast: false
