cam_publisher_node:
  ros__parameters:
    station_id: 1
    wheel_radius: 0.3
    wheel_width: 0.2
    wheel_base: 2.5
    wheel_tread: 1.6
    front_overhang: 0.8
    rear_overhang: 0.8
    left_overhang: 0.5
    right_overhang: 0.5
    vehicle_height: 1.5
    max_steer_angle: 0.785
